### ISSUE TITLE
Error applying moveSectionDown method

### ISSUE THREAD

**Issue by versionmj** [alvarotrigo/vue-fullpage.js#102]
The following error appears in the console as my app loads, although basic section scrolling appears to be working:

![image](https://user-images.githubusercontent.com/48264503/53924788-6738a080-404b-11e9-97db-07d5e4eccfe6.png)

This error appears when I click a button with a v-on directive [ @click="$refs.fullpage.api.moveSectionDown()" ]:

![image](https://user-images.githubusercontent.com/48264503/53924808-791a4380-404b-11e9-8733-001833316e99.png)

I have included both issues in this post because I do not know whether they are related.

FYI, this is my first Vue.js app and my first time using GitHub.

**Comment by dobromir-hristov** [comment]
We would need to see some code. Could you create a codesandbox or some jsfiddle showcasing how you are using fullpage :)

**Comment by versionmj** [comment]
@dobromir-hristov Thanks for your reply.  I actually figured out the issue while creating a codepen per your suggestion.

**Comment by jamespurnama1** [comment]
### Description
I am facing the same problem
Maybe @versionmj can guide me to his solution.
```
|-main.js
|-app.vue
  |-page1.vue
  |-page2.vue
```
Trying to access fullpage API in several ways:
1. I am unable to use $refs since the fullpage instance is on a sibling component, so I used Id instead:
 ```javascript
document.getElementById('fullpage').api.moveTo(0)
```
`Cannot read property 'moveTo' of undefined"`

2.  fullpage_api returns undefined
```javascript
fullpage_api.moveTo(0);
```

### Link to isolated reproduction with no external CSS / JS
I could not reproduce on CodePen since I am working with single file components (.vue files)

### Steps to reproduce it
1. Import fullpage globally

```javascript
// main.js
import VueFullPage from 'vue-fullpage.js';
Vue.use(VueFullPage);
```
2. Create .vue with fullpage
```html
<!-- page1.vue -->
<full-page ref="fullpage" :options="options" id='fullpage'>
  <div class="section">
    <h3>Section 1</h3>
  </div>
  <div class="section">
    <h3>Section 2</h3>
  </div>
  <div class="section">
    <h3>Section 3</h3>
  </div>
</full-page>
```
3. Call method on another .vue component
```html
<!-- page2.vue -->
<template>
  <button @click='scrollToTop()'>
    scroll
  </button>
</template>
<script>
export default {
  methods: {
    scrollToTop() {
      document.getElementById('fullpage').api.moveTo(0);
    },
  },
}
</script>
```
### Versions 
Chrome, Safari, Firefox
MacOS Big Sur

**Comment by alvarotrigo** [comment]
> I could not reproduce on CodePen since I am working with single file components (.vue files)

Try reproducing it in https://codesandbox.io/ or https://stackblitz.com/edit/angular-nqsqwk then :)

**Comment by jamespurnama1** [comment]
> > I could not reproduce on CodePen since I am working with single file components (.vue files)
> 
> Try reproducing it in https://codesandbox.io/ or https://stackblitz.com/edit/angular-nqsqwk then :)

Here you go:
https://codesandbox.io/s/fullpagejs-20j19

**Comment by alvarotrigo** [comment]
What do you mean when you say 

> fullpage_api.moveTo(0) // returns undefined

It seems to work properly for me.
It returns to section 0 when in any other.
