### ISSUE TITLE
navigation-anchornames also appearing in slidesNav when anchors-Option is added

### ISSUE THREAD

**Issue by dstN** [alvarotrigo/vue-fullpage.js#158]
First of all: I had to learn it the hard way, that there is no basic-css included in this vue component, so you have to style the slides for yourself for them to work. (floating / positioning stuff)
**//Edit: This was my bad. It's literally written on the github page. I'm sorry!**

Now to my issue:
I have 4 sections, third section has 12 slides
if i use the option "anchors", "slidesNavigation" and "navigation" the slidesNav-UL has the section-anchors as text as well. 

navigation has all the anchors of the sections - in a correct order.
slidesNavigation UL has correct amount of list items, but the first 4 are named by the anchors given in the options.

if i remove the anchors option the naming is gone, but my navigation also doesn't work anymore.

how to get rid of the naming in slidesNavigation?

Also happening on your main site as well. https://alvarotrigo.com/fullPage/#page2

you only styled it in a way (the dot-navigation) that the user can't see it.

**//Edit ok, i now realized those things are screenreader only - BUT still getting wrong Info then.**

**Comment by alvarotrigo** [comment]
I imagine you are talking about the `<span class="fp-sr-only">fullPage</span>` part?
It definetely seems like a bug :)

However, notice there are no tooltips for horizontal slides. Only for vertical ones.
Those values are only for screen readers, thus the name `fp-sr-only`.

Can you please open an issue about this on the fullPage.js repository? As this is not a vue-fullpage.js issue?
https://github.com/alvarotrigo/fullPage.js/issues

Thanks. I'll proceed to close this issue here.
