### ISSUE TITLE
Vue events are no longer called when fullpage is rebuild with build.

### ISSUE THREAD

**Issue by DanielHartUK** [alvarotrigo/vue-fullpage.js#63]
When the build method is called on vue-fullpage.js, any Vue event listers on an element within a Fullpage section or slide no longer work. 

See demo on [Codepen](https://codepen.io/DanielHartUK/pen/bmxZXj), note that the 'Hello' button on the first section will display an alert, however once a section is added and Fullpage is rebuilt, pressing the button no longer displays that alert.

This issue also affects Vue components, where the component is displayed inside of a Fullpage section/slide.

**Comment by alvarotrigo** [comment]
Thanks for reporting it! I'll check it out whenever I can!

**Comment by i22tha** [comment]
Having the same issue with Vue components inside Fullpage Slides (not Sections).

**Comment by indigo-michael** [comment]
I'm having the exact same issue :(

**Comment by dobromir-hristov** [comment]
I had a deeper look into this and the `destroy('all')` is what is really screwing it up. From what I can gather, Fullpage has the DOM cached and when you "return everything to normal", that essentially removes all of the Vue watchers on the DOM.

Problem is that you cannot just ask Vue to "re-watch" the DOM. In many cases, that would require the none-runtimeonly build, because otherwise Vue wont know what a DOM element is, as under the hood, the build system transforms .vue components to plain render functions. 

I did however do a normal `destroy` and then rebuild and it worked, but that leaves elements "changed".

**Comment by alvarotrigo** [comment]
@dobromir-hristov yeap! It seems to be an issue with the DOM structure. More specific, with the creating of the wrapper with the class `fp-tableCell` that gets added by fullpage wrapping the content inside sections when using the default option `verticalCentered:true`.

Using `verticalCentered:false` solves it as can be seen here:
https://codepen.io/alvarotrigo/pen/YRWNWN

In any case, this issue was solve some time ago on the dev branch of the fullPage.js library:
https://github.com/alvarotrigo/fullPage.js/pull/3436

So I've just updated the dist files in the vue project to fix it.
I'll mark it as fixed!

Should be merged in version 0.1.0 of vue-fullpage.js

**Comment by dobromir-hristov** [comment]
Awesome! I was actually about to look for such a thing :)

**Comment by alvarotrigo** [comment]
@dobromir-hristov thanks for your help tho!!
