### ISSUE TITLE
Improve docs regarding Nuxt.js compatibility

### ISSUE THREAD

**Issue by alvarotrigo** [alvarotrigo/vue-fullpage.js#73]
Regarding the conversation in the issue https://github.com/alvarotrigo/vue-fullpage.js/issues/6, we need a way to clarify how to use the vue wrapper when using it together with Nuxt.js.

Any help will be appreciated!

**Comment by dobromir-hristov** [comment]
From what I am understanding, we need a guide in the docs on how to import Fullpage as a nuxt plugin and set it as `ssr:false`?

**Comment by alvarotrigo** [comment]
@dobromir-hristov whatever you think it is necessary to avoid people opening issues like this one: https://github.com/alvarotrigo/vue-fullpage.js/issues/6

**Comment by dobromir-hristov** [comment]
Will do.

**Comment by dobromir-hristov** [comment]
I played around with this and here is what I have.
1. If we define the plugin with `ssr:false` in the plugins definition, it works, but gives out a warning, saying the dom has changed. This is normal as the plugin is bootstrapped after the dom has rendered on the server side.
2. If we define the plugin as normal, it errors out because we import full-page directly, which accesses the `window` object. I did try to wrap it in a dynamic import so it only gets imported on `mount`, but I am getting lots of errors there.
3. Using the `<no-ssr>` component works, but then the whole slot of the full-page component is gone, meaning your SSR website will be empty to crawlers, which defeats the purpose of SSR.

**Comment by alvarotrigo** [comment]
Thanks for that!
What are your thoughts on it then? Should we go for the 1st option?

**Comment by dobromir-hristov** [comment]
Think so. Easiest to do. Best case scenario would be to load everything on `mounted` so it doenst break. Also could use `process.browser` but I could not make it work like that.

**Comment by alvarotrigo** [comment]
Sounds good to me! 
Please feel free to commit a PR with your proposed solution.

**Comment by alvarotrigo** [comment]
Merged in 0.1.0!
