### ISSUE TITLE
Anyway to delay fullpage's destroy method until after router leave transition completes?

### ISSUE THREAD

**Issue by alexhillel** [alvarotrigo/vue-fullpage.js#81]
I'm currently using transitions between routes in Vue/Nuxt, and the leaving component containing a Fullpage.js subcomponent is destroyed before my leave transition completes. This causes all styles to be removed from fullpage component whilst still visible, and looks bad. 

Is there the ability to override the fullpage destroy call in the components lifecycle method, and manually call it after the leave transition is complete?

**Comment by dobromir-hristov** [comment]
Its getting destroyed on "beforeDestroy" so if you are using the `mode="out-in"` you should not see it being destroyed because the new one would probably be in View before it gets to the point of destruction. 

There is currently no way to stop destruction of the full page component in the beforeDestroy hook. Adding an extra prop would add unnecessary complexity that is potentially dangerous. Not auto destroying the component could lead to nasty side effects.

**Comment by alvarotrigo** [comment]
Perhaps you can consider fading the whole page out even before fullPage.js gets destroyed?
Before even changing the route?

**Comment by alexhillel** [comment]
My transition keeps the old view visible for about a second, and there is a definite visible collapsing of the fullpage managed elements. An extra prop to disable the auto destruction of the element (defaulting to false of course) would make this plugin usable for longer transitions, as i could manually call `window.fullpage_api.destroy()` from within the transition hook. I'm not sure why this would be dangerous with a sensible default.

**Comment by alexhillel** [comment]
That may be the best option. I'll investigate putting logic in a `beforeRouteChange` guard.

**Comment by damienroche** [comment]
@alexhillel do you find a solution without fade out the page ? i'm stuck with this issue...
https://v.usetapes.com/xVBon0cowx

**Comment by TranceGeniK** [comment]
Same issue here, has anybody found a solution ?

**Comment by YongzeYao** [comment]
Same issue here, anybody found a solution?

**Comment by 2ngddo** [comment]
Same issue here, anybody found a solution?

**Comment by TranceGeniK** [comment]
I went with the `beforeRouteChange` guard, it's better but still not ideal

**Comment by alexhillel** [comment]
Same here with the `beforeRouteChange` guard. It works but it feels a little hacky and unintuitive.

**Comment by gennbo** [comment]
Can anyone share a working example?

**Comment by TranceGeniK** [comment]
Not sure if it's the best way but here is an example
https://pastebin.com/JEXN2uGB

**Comment by alvarotrigo** [comment]
I believe this Vue mixin can probably solve these kind of issues?
https://github.com/diachedelic/vue-removed-hook-mixin

From their docs:

> The built in destroyed hook is called before a component is fully transitioned out of view, which is a problem if destroying your component changes how it looks. For instance, a Leaflet map, once destroyed, immediately removes all its tiles and becomes an unsightly grey box. My only options was to wait until the transition was finished and my component out of view, and then destroy my Leaflet map. However, detecting the end of transitions is unreliable, so I opted to wait until the component's root element was removed from the DOM.

**Comment by CHEWX** [comment]
Also use the `beforeRouteLeave` hack. Not ideal, but doesn't seem to be another way.

**Comment by CHEWX** [comment]
Sandbox here for anyone wanted to see the issue — https://7fvj9.sse.codesandbox.io/

1. Click "here" on second screen.

**Comment by alvarotrigo** [comment]
@CHEWX have you tried the vue-removed-hook-mixin I talked about?

**Comment by csoalhat** [comment]
Has anyone found a good hack for this or has used the vue-removed-hook-mixin successfully? I cant figure out how to use it properly.

**Comment by alvarotrigo** [comment]
@dobromir-hristov what do you think about this case? 
Do you find any better solution than by using the vue-removed-hook-mixin I mentioned before?

**Comment by dobromir-hristov** [comment]
I think that is the way to go.

**Comment by CHEWX** [comment]
@alvarotrigo Please can you fork my sandbox (above) that shows the issue and show an example with `vue-removed-hook-mixin` as there are a few of us that haven't successfully implemented this route.

**Comment by alexguevara** [comment]
Does anyone succees with `vue-removed-hook-mixin`? I`m stuck with it.

**Comment by TranceGeniK** [comment]
https://github.com/alvarotrigo/vue-fullpage.js/blob/master/src/FullPage.vue#L38

Would it be possible to set an option to destroy only events here so styles would remain in place?

**Comment by CHEWX** [comment]
Still confused why this issue is closed? @alvarotrigo

**Comment by TranceGeniK** [comment]
@alvarotrigo the above PR solves part of the issue, it's working fine when the page is on the first section. However, the page still jumps back to the first section (the transform on the fullpage wrapper goes to 0,0,0) while the page is transitioning. 
Any idea how to avoid that ?

**Comment by alvarotrigo** [comment]
@TranceGeniK I don't see why that should happen. The destroy method won't change the scrolling unless using the param `all`. You can test this by yourself on the [vue-fullpage demo page](https://alvarotrigo.com/vue-fullpage/#page2) by running `fullpage_api.destroy();` in the js console.

**Comment by TranceGeniK** [comment]
On the demo page, when I run `fullpage_api.destroy();`, there is a scrollbar appearing and the div.fullpage-wrapper inline style style is set to `transform: translate3d(0px, 0px, 0px);`
On my page it was jumping because I set the height to 100vh so the overflow was hidden. I could allow the overflow but I don't want this behavior because it causes a scrollbar to appear while the page is transitioning, it's not pretty ^^
I'd just like the transform to stay as it is before calling the destroy method. Is there a way to do this ?

**Comment by alvarotrigo** [comment]
> I'd just like the transform to stay as it is before calling the destroy method. Is there a way to do this ?

That sounds like that's your own case scenario then :) 
The way fullpage.js works now, it destroys the autoScrolling effect when removing fullpage.js events, and that implies removing any transformation applied ton the wrapper. 

I don't think we can scroll the page to the top when removing the scrollbar, so in your case, I guess you would have to call `fullpage_api.silentMoveTo(DESTINATION_INDEX + 1);` again after the destroy.

So, if you want to move to section 3, `fullpage_api.silentMoveTo(3);`. You can detect which sectin is active by checking for the `active` class in a section. So basically  `.fp-section.active` will be the active one.

**Comment by TranceGeniK** [comment]
> That sounds like that's your own case scenario then :)
Yeah, kind of, but I think I'm not the only one in this scenario. 
The issue is that the styles are applied when destroying the component, so I'm not sure I can do anything at this point in the component lifecycle.
I've tried replacing beforeDestroy in vue-fullpage.js with the vue-removed-hook-mixin you mentioned above and it's working better than just calling destroy without 'all' in this case.
Would you allow it as a dependency ?

**Comment by alvarotrigo** [comment]
> The issue is that the styles are applied when destroying the component, so I'm not sure I can do anything at this point in the component lifecycle.

They don't get removed when only using `destroy` as you did on your pull request.

**Comment by TranceGeniK** [comment]
Sorry, my English isn't very good, I have a hard time explaining myself ^^
The issue is not that styles are removed, it's the autoScrolling being disabled like you said earlier that makes the page go to the top in this case. 
So the way it is now, either I have to accept the scrollbar flashing during my leave transition, or the page jumping to the top. Until now, I waited for the page to fade out to destroy but it's not a desirable behaviour.
I would need to keep the autoScrolling transformations as they are when destroying, or use the removed hook in vue-fullpage to achieve the desired effect.

**Comment by alvarotrigo** [comment]
> So the way it is now, either I have to accept the scrollbar flashing during my leave transition, or the page jumping to the top.

And that's why I suggested you to keep applying your change and then just use the `silentMoveTo` method to prevent the page from scrolling to the top and keeping it focusing the active section.

**Comment by TranceGeniK** [comment]
Yeah I understood that, problem is that vue-fullpage beforeDestroy method is called after the parent component beforeDestroy, so I can't call `silentMoveTo` after :/

**Comment by alvarotrigo** [comment]
You can add it in the pull request, just after the destroy call. Won't cause any harm for other use cases.

https://github.com/alvarotrigo/vue-fullpage.js/pull/167/commits/f42de0a8c4aaae64e62a6f10708b95ef50842e9d#diff-0a4437b0cc9c482ff72b0a86f5320cf5R39

**Comment by TranceGeniK** [comment]
Just tried it, doesn't seem to do do anything...
I'm just going to use the removed hook on my fork, this seems to be the easiest solution
Thanks for the help :)

**Comment by alvarotrigo** [comment]
@TranceGeniK can you create a public URL were we can test the use case?

**Comment by CHEWX** [comment]
I think @TranceGeniK issue should be opened in a new issue, it's not the issue at hand here.

Out the box the issue is with fullpage destroying too early as per — https://github.com/alvarotrigo/vue-fullpage.js/issues/81#issuecomment-532532663

**Comment by alvarotrigo** [comment]
> I think @TranceGeniK issue should be discussed within his PR. Keep this issue clean.

Agree! :) Thanks for the heads-up! 👍

**Comment by TranceGeniK** [comment]
Actually, this is the same issue, the PR is just a proposed solution to it, but after consideration it doesn't solve everything related. I'm trying to put together a simple test page

**Comment by TranceGeniK** [comment]
Here is a test page : https://trancegenik.github.io/vue-fullpage-issue-81-test-pages/
And the code : https://github.com/TranceGeniK/vue-fullpage-issue-81-test

I didn't include the PR here, for you to see the initial issue

**Comment by alvarotrigo** [comment]
@TranceGeniK can you provide the reproduction with your PR too?

**Comment by TranceGeniK** [comment]
Yes, code is in the same repo, in the with-pr branch
Test page here : https://trancegenik.github.io/vue-fullpage-issue-81-test-with-pr-pages/
I didn't manage to remove the `Fullpage.js can only be initialized once and you are doing it multiple times!` error here (weird because I don't have it on my main site but I don't want to spend to much time on this now), so you will have to refresh the page to test it multiple times.

**Comment by TranceGeniK** [comment]
And here's one with the removed hook (with-removed-hook branch for code)
https://trancegenik.github.io/vue-fullpage-issue-81-test-with-removed-hook-pages/

**Comment by cuberinooo** [comment]
any news on this ? Would like to use vue transition but fullpage get destroyed after view is changed via vue route
